hrsh7th/nvim-cmp

README.md
Add defaults and change wording.
=> Update documentations for config

.github/workflows/integration.yaml, Makefile, utils/install_stylua.sh
=> install stylua without cargo

Makefile
=> Fix stylua glob typo

README.md
A mapping example that was frequently asked about has been added to README.md.
Sorry, but I don't use vsnip, so if you prefer that, please adjust accordingly.
=> Add mapping example to README

lua/cmp/menu.lua
Alright alright, I realize that you are probably tired of #111 already, but I have found a pretty serious bug related to deduplication, which you removed in commit e599f0825cc6de637a70aee9b941698417d27768. As an example, let's say that the following completion list has to be displayed:
```lua
{
{
abbr = "print(...)~",
dup = 1,
empty = 1,
equal = 1,
kind = "Snippet",
user_data = { cmp = 1911 },
word = "print"
}, {
abbr = "print",
dup = 0,
empty = 1,
equal = 1,
kind = "Text",
user_data = { cmp = 1709 },
word = "print"
}, {
abbr = "printf(...)~",
dup = 1,
empty = 1,
equal = 1,
kind = "Snippet",
user_data = { cmp = 1912 },
word = "printf"
}, {
abbr = "vim_print",
dup = 0,
empty = 1,
equal = 1,
kind = "Text",
user_data = { cmp = 1126 },
word = "vim_print"
}
}
```
The first three entries come …
=> Bring back the duplicates filter due to shifting completion item indexes after deduplication (continuation of fixes for #111)

lua/cmp/float.lua
fix #150
The problem arises when the left or right space is unable to accommodate the floating doc. This PR fix it by computing them and adjust the maxwith before getting the actual width.
=> Fix float document not displaying

lua/cmp/core.lua
Do not loop twice over sources table, instead keep a table mapping names
to sources
=> Slight complexity reduction

lua/cmp/core.lua
Change sources table to hold a table mapping source name to a table of sources.
Solves Issues raised in #195
=> Rework #195

README.md, lua/cmp/config.lua, lua/cmp/init.lua, lua/cmp/source.lua, plugin/cmp.lua
Fixes #95, #61
I've added a feature that shows the current source's status.
But I'm not familiar with the interface design 😢
So it is possibly inconvenient. Please feel free to advise me.
=> RFC: `CmpStatus` command

README.md
Fix some typos and errors in `README.md`.
=> Fix and improve README.md

lua/cmp/view/ghost_text_view.lua
Previously if the completion entry text had a multibyte character the
ghostly text renderd improperly, for example:
The cursor position is "|"
In this case the ghost text was spliting a multibyte character.
In this case the multibyte had passed messing up the indexing therefore presentin the last character of the entry as ghost text.
=> fix(ghost_text): generate it using chars instead of bytes

README.md
Added instruction for icons and source without extra plugin.
=> Link to menu appearance page in wiki

README.md, lua/cmp/config.lua, lua/cmp/config/default.lua, lua/cmp/source.lua, lua/cmp/types/cmp.lua, lua/cmp/utils/misc.lua, lua/cmp/utils/misc_spec.lua
- SourceConfig.opts -> SourceConfig.option
- Add SourceConfig.trigger_characters
- Allow accessing full SourceConfig from source
=> Allow to take the full SourceConfig from source API

README.md
=> Update readme: add a link to a list of cmp sources

.github/ISSUE_TEMPLATE/bug_report.yml
=> Change URL of FAQ in bug_report

lua/cmp/utils/buffer.lua
As discussed in https://github.com/hrsh7th/nvim-cmp/pull/886#issuecomment-1098596708, the issue @bbbert was experiencing has been fixed in airline. So I think it's ok to revert #886.
=> Revert #886 and refactor

README.md
Improve the README instruction on where to find breaking changes. Included a suggestion to subscribe to the github issue to get notified about changes.
=> docs!: improve the instructions to follow breaking changes (#231)

doc/cmp.txt
As a start, will say I adore that plugin! But disturbing thing was that docs aren't comprehensive or correct sometimes(no offense), that's why i attempted to fight against it and rewritten huge part of the doc.
- Be short and expressive
- Follow grammar rules
- Maintain default structure of help file
=> Help page changes.

doc/cmp.txt
=> Fix doc typo

doc/cmp.txt, lua/cmp/config/default.lua, lua/cmp/core.lua, lua/cmp/types/cmp.lua
=> make debounce and throttle time configurable

doc/cmp.txt, lua/cmp/config/default.lua, lua/cmp/config/window.lua, lua/cmp/view/custom_entries_view.lua
Hi! Previously I opened #846 to see about exposing some configuration options of the completion window to users. With some of the recent changes you made, this became very simple to implement. Let me know if this is mergeable, or if I need to add anything else.
=> Add Completion Window Options

lua/cmp/entry.lua
=> add check for nil on documentation.value

lua/cmp/entry.lua, lua/cmp/init.lua, lua/cmp/source.lua, lua/cmp/utils/async.lua
CI is failing on the `stylua --check`, so I formatted it with stylua.
`make integration` still fails vusted, but it didn't seem like it would be fixed right away, so I would like to PR just the format first.
=> Format by stylua

lua/cmp/utils/keymap.lua
see comments on #1213
cc @briandipalma @appelgriebsch
=> fix compatibility with nvim < 0.8

README.md
See https://github.com/hrsh7th/nvim-cmp/discussions/941.
=> README.md: don't set 'completeopt'

lua/cmp/view/custom_entries_view.lua
=> fix: prevent autocmd outbursts by using setcmdline instead of feedkey

lua/cmp/view/custom_entries_view.lua
Fix for https://github.com/hrsh7th/nvim-cmp/issues/1455
=> fix: better check for if setcmdline() is available

lua/cmp/view/custom_entries_view.lua
Addresses the comment left in https://github.com/hrsh7th/nvim-cmp/issues/1455
=> fix: in lua if(0) evaluates to true, so check vim.fn.has == 1

lua/cmp/view/custom_entries_view.lua
=> fix(cmdline): properly compute string length

lua/cmp/entry.lua, lua/cmp/entry_spec.lua
- Fixed regression with clangd
- Added regression test
=> fix 1533, add regression test

lua/cmp/view/ghost_text_view.lua
Quick fix for using new inline virtual text.
Before merging I'll figure out how to feature gate it behind "inline" actually being available
=> ghost text inline

lua/cmp/utils/feedkeys.lua
=> feat: avoid global variable use

lua/cmp/view/ghost_text_view.lua
Fix: https://github.com/hrsh7th/nvim-cmp/issues/1818
=> fix(ghost_text): make sure to the delete the mark for the same buffer

lua/cmp/entry.lua
=> follow vscode's resolve behavior

lua/cmp/view/custom_entries_view.lua, lua/cmp/view/native_entries_view.lua, lua/cmp/view/wildmenu_entries_view.lua
fix error in #1986, maybe
This error does not occur on my end, so I am anticipating and fixing it. I would like to see if this branch will fix it.
@monheimx9, @curiousignite, @0xDmtri, or anyone else.
=> fix(view): check in get_selected_index

lua/cmp/utils/keymap.lua, lua/cmp/utils/keymap_spec.lua
Fix https://github.com/hrsh7th/nvim-cmp/issues/2070 https://github.com/hrsh7th/nvim-cmp/pull/1935#issuecomment-2442337135
=> fix: make <c-;> work again

lua/cmp/utils/keymap.lua, lua/cmp/utils/keymap_spec.lua
Identical fix to https://github.com/hrsh7th/nvim-cmp/pull/2073
=> fix: make <c-'> work again
