hrsh7th/nvim-cmp

README.md
`cmp` is used in `mapping` but not defined.
=> Add `local cmp = require('cmp')` in README.md

README.md
the current supertab example was causing autocompletion to break because `vim.api.nvim_replace_termcodes` requires 4 parameters and the example was only passing one.
Added a function to extract it and input the remaining required parameters.
=> fixed supertab example

README.md
Noticed a few minor grammar issues in the readme while I was setting up `nvim-cmp`; here's a PR with some fixes. 
Love the project, thanks for all the hard work!
=> fix some README grammar

README.md, lua/cmp/config/default.lua, lua/cmp/core.lua, lua/cmp/menu.lua, lua/cmp/types/cmp.lua
This PR adds the ability to show the first candidate's preview as inline.
This is still a much experimental feature. I think we should remove this feature after VSCode's ghost text feature ships to LSP spec.
https://user-images.githubusercontent.com/629908/131284635-74da4ef7-289e-440a-abe8-bb36dc6af279.mp4
=> Experimental: Ghost text

Makefile, lua/cmp/config/compare.lua, lua/cmp/config/default.lua, lua/cmp/types/cmp.lua, lua/cmp/types/init.lua, lua/cmp/types/lsp.lua, lua/cmp/types/lsp_spec.lua, lua/cmp/types/vim.lua, lua/cmp/utils/async.lua, lua/cmp/utils/async_spec.lua, lua/cmp/utils/cache.lua, lua/cmp/utils/char.lua, lua/cmp/utils/keymap.lua, lua/cmp/utils/misc.lua, lua/cmp/utils/misc_spec.lua, lua/cmp/utils/pattern.lua, lua/cmp/utils/spec.lua, lua/cmp/utils/str.lua, lua/cmp/utils/str_spec.lua
Fixed StyLua's glob pattern to be enabled.
[Needed to be enclosed in quotation marks, as in `--glob 'lua/**/*.lua'`.](https://github.com/JohnnyMorganz/StyLua#glob-filtering)
The style has also been fixed.
=> fix StyLua command

README.md
This commit fixes an issue with using vsnip#anonymous in the snippet expand function for Ultisnip
The main issue, is that when using `vsnip#anonymous` instead of `UltiSnip#Anon` when calling the `cmp.mapping.confirm` map on a non-snippet option would "crash" cmp, ceasing its normal functionality. Using `UltiSnps#Anon` fixes this issue.
=> Fix: bad function usage in README for UltiSnips expansion

README.md, lua/cmp/config/default.lua, lua/cmp/config/mapping.lua, lua/cmp/init.lua, lua/cmp/types/cmp.lua, lua/cmp/view.lua, lua/cmp/view/custom_entries_view.lua
Following up on this https://github.com/hrsh7th/nvim-cmp/pull/224#issuecomment-925111914 I started to check the code, and it might make sense to insert on each selection, this might be a design choice, but this would add a configuration option that disables this behavior, making the `select_prev_item()` and  `selec_next_item()`  just move through the menu without inserting until `confirm()` is called.
these are some examples with the config combination
```
mapping = {
["<C-p>"] = cmp.mapping.select_prev_item{behavior = cmp.SelectBehavior.Select},
["<C-n>"] = cmp.mapping.select_next_item{behavior = cmp.SelectBehavior.Select},
},
experimental = {
ghost_text = true,
},
```
https://user-images.githubusercontent.com/18682359/134438815-d2914d1a-ce66-4137-b14d-73bf7ac514ba.mov
```
mapping = { …
```
=> Improvement idea: option to disables insert on select item

lua/cmp/config/mapping.lua, lua/cmp/utils/api.lua
Mappings for visual mode are useful, for example, in snippets.
[Here](http://vimcasts.org/episodes/ultisnips-visual-placeholder/) is the vimcast which shows how it can be used.
=> Add mappings for visual mode

README.md
I don't use a snippet plugin normally and I was running to issues with autocompletion until I came across [this comment](https://github.com/hrsh7th/nvim-cmp/issues/274#issuecomment-939500416).
Therefore, I think it's best to clearly document that a snippet engine is required at the moment. Adds comment to suggested sample and the FAQ.
=> README: clarify that a snippet plugin is required

lua/cmp/utils/misc.lua, lua/cmp/utils/misc_spec.lua
Before this change:
1. `misc.merge({a = misc.none}, {a = nil})` returned `{a = misc.none}`
2. `misc.merge({a = nil}, {a = misc.none})` returned `{a = misc.none}`
(1) can cause error if a non-existing mapping is set to `config.disable`
(which is an alias for `misc.none`).
(2) does not cause any issue to date, but is inconsistent with the
expected behavior of `misc.merge(…)`.
After this change:
1. `misc.merge({a = misc.none}, {a = nil})` returns `{a = nil}`
2. `misc.merge({a = nil}, {a = misc.none})` returns `{a = nil}`
Fixes #440.
=> misc.merge: ensure that `misc.none` is never returned

lua/cmp/utils/keymap.lua
In `keymap.autoindent`, `!^F` is added to `indentkeys`, then `<C-f>` is
fed.  In the end `indentkeys` is reset to its original value.
We need to escape any `|` in `indentkeys` when setting the option
because otherwise they are seen as the command separator.
=> Escape <Bar> when setting indentkeys

lua/cmp/view/docs_view.lua
Small PR that updates the documentation floating window to use the 'linebreak' option in Vim so that when text wraps, the whole word is moved to the next line if it's too long for the current line. In my opinion, it makes it much easier to read the docs 😃. You can see what I mean below.
Before this PR:
After this PR:
If you don't want to accept this change, I'd love if we could add a custom filetype for the Documentation window so that at least for myself, I can write an autocmd that sets the 'linebreak' option in my own config for the documentation window. I'd be happy to refactor this PR to do that if you'd prefer. Maybe there's already something in nvim-cmp that I can hook into that I am just not aware of instead of adding this new change, if so I'd love to hear about it!
Thanks for …
=> Add linebreak option to cmp documentation window

README.md, lua/cmp/config/mapping.lua, lua/cmp/init.lua
Allow to specify the reason (or any other context options) when calling `cmp.mapping.complete`
fix #528
=> Add reason to complete function

README.md
A better key mapping, corresponding to `<C-f>`, for scrolling docs backwards is `<C-b>` because it is used for scrolling backwards in Vim (`:h CTRL-B`).
If you have purposely written `<C-d>`, close this PR. Thanks.
=> Fix document about scrolling docs backwards

lua/cmp/source.lua
This fixes the following error that occurred when trying to expand a `luasnip` choicenode snippet at the start of a line:
```lua
Error executing vim.schedule lua callback:
.../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:240:
bad argument #1 to 'byte' (string expected, got nil)
```
=> Fix possible nil argument to string.byte

lua/cmp/view/native_entries_view.lua
Previously we didn't do this, which resulted in the documentation window
not being shown when switching through different completion items. Fix
this by firing the change event in select_next_item and select_prev_item.
=> Fire change events when selecting different items with native menu completion

doc/cmp.txt
helptags were failing with an error:
```
Error detected while processing /home/perrin4869/dotfiles/home/.config/nvim/after/plugin/helptags.vim:
line    4:
E154: Duplicate tag "cmp-config.formatting.fields" in file /home/perrin4869/.local/share/nvim/site/pack/default/start/nvim-cmp/doc/cmp.txt
E154: Duplicate tag "cmp-config.snippet.expand" in file /home/perrin4869/.local/share/nvim/site/pack/default/start/nvim-cmp/doc/cmp.txt
```
This is the fix.
Thanks!
=> Fix duplicate doc tags

lua/cmp/utils/highlight.lua, plugin/cmp.lua
`highlight! default` overrides the existing highlight in order to set a default link. So any highlight group that exists before will be wiped over.
To fix this I have changed `highlight! default` to `highlight default`, which only sets the highlight group if it wasn't already defined.
=> fix: default highlights overriding existing highlights

README.md
I just noticed this while reading the setup section.
Compare
with
Especially the comments look nicer imo.
=> Readme: improve readability of lua code block in setup section

lua/cmp/entry.lua, lua/cmp/utils/buffer.lua, lua/cmp/utils/window.lua, lua/cmp/view/custom_entries_view.lua
What I mean by "wide characters" are characters which require more than one column to be rendered. Examples of such characters include:
- CJK characters
- Emoji
- The `<Tab>` character
- Special unprintable characters (for example, from 0 to 31 in the ASCII table) - this one is Vim-specific because Vim renders them as `<xx>` or `^X` (see [`:help 'isprint'`](https://neovim.io/doc/user/options.html#'isprint'))
Because these characters are wide, using `vim.str_utfindex` is not an accurate way of getting the width of a string as it will be rendered on the screen. The solution is to use the Vimscript function `strwidthdisplay`, which is what this PR is for. However, most of the changes in this PR were done for calling `strwidthdisplay` within the entries window's buffer.
Here are some …
=> Fix rendering of completion items with wide characters in the custom entries window

doc/cmp.txt
=> Correct vim doc reference for getcmdtype()

lua/cmp/view/native_entries_view.lua
=> Fix `vim.fn.complete` being constantly called by the `native_entries_view`

lua/cmp/view/docs_view.lua
Unless manually configured, the current default zindex for documentation is 1.
This limits the flexibility of other floating windows to have lower zindex, since 1 is the lowest.
This PR changes the default zindex to 50 for documentation floating windows, to match Neovim's default zindex for floating windows.
I see that the default of 1 is specified in [window.lua](https://github.com/hrsh7th/nvim-cmp/blob/9c07c2d1c5581b22f742b891cadd42a311c1cf96/lua/cmp/utils/window.lua#L89). If the idea of changing default documentation zindex is acceptable, that would seemingly be an alternative place to make the change, and have the benefit that it would apply for all floats, not just documentation.
I noticed this in an attempt to address an [issue](https://github.com/dstein64/nvim-scrollview/issues/60) …
=> Use a default zindex of 50 for documentation

doc/cmp.txt, plugin/cmp.lua
I was bored, so I browsed the codebase to learn more about how nvim-cmp works.
I changed `cmp#ready` to `CmpReady` because I was confused with the naming convention; I thought it was an autoloaded function. I think the naming convention for User event autocommand patterns is upper camel-case. I also added a description in the docs on how to use these autocommands.
Please feel free to disregard if you disagree with any of these changes.
=> Change cmp#ready to CmpReady and document autocmds better

lua/cmp/entry.lua
Completion results returned by https://github.com/dcampos/cmp-snippy are like this - that source defines an `execute` function which calls nvim-snippy directly, instead of letting nvim-cmp handle snippet expansion.
=> Add the snippet indicator for items with Snippet kind

plugin/cmp.lua
Reading the doc it seemed I could set `CmpItemKind` to override all item kind. Am I missing something?
=> Default CmpItemKind%name% to CmpItemKind

doc/cmp.txt
`autocmd` notation is invalid in the FAQ session.
The way it is set it generates an "E20: Mark not set" error when buffer of given filetype is opened.
This PR set correct `autocmd` notation.
=> Fix docs to avoid "E20: Mark not set" error

lua/cmp/init.lua
A scenario where this lead to unintended behaviour previously was the following:
If cmp.enabled was configured such that it disabled cmp when in a comment,
and the user typed `--` in a lua file (this starts a comment), the cmp window
would not close if further text is typed on that line (although cmp should be disabled).
---
I have the following in my config:
```lua
enabled = function()
local in_prompt = vim.api.nvim_buf_get_option(0, "buftype") == "prompt"
if in_prompt then
return false
end
local context = require("cmp.config.context")
return not(context.in_treesitter_capture("comment") == true or context.in_syntax_group("Comment"))
end,
```
To see what the issue is, have a look at the following GIF:
This PR should fix it:
Let me know if there is a better way to fix this :)
=> Fix: close the view if cmp.enabled = false and the user types some text

lua/cmp/core.lua, lua/cmp/types/cmp.lua
Currently it seems there is no way for someone listening to the
`confirm_done` event to know exactly what character was used to commit
the completion confirmation.
This commit adds a `event_chars` property to the `confirm_done` event.
Its value is just the `chars` variable form the `core.on_keymap`
function.
This should help resolving a double parentheses issue with nvim-autopairs (#780).
=> Added `event_chars` property to `confirm_done event`

lua/cmp/config/context.lua
Not sure why returning `{}` was required (see discussion at https://github.com/hrsh7th/nvim-cmp/pull/676#discussion_r782408306).
Now we can omit the `== true` check in
```lua
enable = function()
local context = require("cmp.config.context")
return not (
context.in_treesitter_capture("comment") == true or context.in_syntax_group("Comment")
)
end
```
-->
```lua
enable = function()
local context = require("cmp.config.context")
return not (
context.in_treesitter_capture("comment") or context.in_syntax_group("Comment")
)
end
```
I also simplified the code at the end of the file.
=> Refactor context module, return false instead of {} in `context.in_treesitter_capture`

README.md, doc/cmp.txt, lua/cmp/config.lua, lua/cmp/config/default.lua, lua/cmp/types/cmp.lua, lua/cmp/utils/str.lua, lua/cmp/utils/window.lua, lua/cmp/view/custom_entries_view.lua, lua/cmp/view/docs_view.lua, plugin/cmp.lua
This PR is a followup to #224, adding support for custom borders in the completion menu:
It can be added to any existing config like so:
```lua
cmp.setup {
window = {
completion = { -- rounded border; thin-style scrollbar
border = 'rounded',
scrollbar = '║',
},
documentation = { -- no border; native-style scrollbar
border = nil,
scrollbar = '',
-- other options
},
},
-- other options
}
```
Note: This implementation ~~may~~ also works for `cmdline`~~, though I don't have that in my config so I haven't been able to test it.~~
---
One change I want to highlight is the use of `FloatBorder` for the completion menu. `Pmenu` was being used, but this makes the borders look less like a floating window and more like a box within the existing `pum` window (compare closely with the above screenshot): …
=> feat: completion menu borders

lua/cmp/config.lua
This ensures that the config is at least `{}` and never `nil`.
Otherwise, calling `cmp.setup()` errors out.
=> Make sure config is not nil

lua/cmp/utils/misc.lua
I just use nvim-cmp to test nvimlsp and found the redraw issue for incsearch.
`<C-r><Esc>` is less side effect than `<C-r>=""<CR>`
=> fix(misc): kill redundant redraw during incsearch (#485)

lua/cmp/entry.lua
This fix syntax highlighting when handling files with multiple-filetype.
After fix
If there is a better way to fix this, let me know :)
=> use only the first filetype for formatting

lua/cmp/config/mapping.lua, lua/cmp/utils/misc.lua, utils/install_stylua.sh
The CI/Actions has been broken for a while (we shouldn't be ignoring build errors) and this PR should fix the CI build errors due to stylua.
- Fix code style issues, suggested by stylua
- Update install_stylua.lua script so that it can run in macOS as well.
=> fix: Fix stylua errors and install_stylua script

lua/cmp/config.lua
As reported here: https://github.com/hrsh7th/nvim-cmp/issues/936
=> fix: don't show non-working configuration in deprecation suggestion

plugin/cmp.lua
This moves the creation of the `:CmpStatus` command to the new `vim.api.nvim_create_user_command` API
This requires neovim 0.7 so it should be done along with #844
=> Implement nvim_create_user_command

lua/cmp/utils/highlight.lua, plugin/cmp.lua
This gives a first stab at simplifying the highlighting in `cmp` to use the new `vim.api.nvim_set_hl` lua API.
I did remove the `cterm` and `gui` specific highlights because the `vim.fn.synIDattr` and `vim.api.nvim_set_hl` commands default to the current mode of neovim (i.e. gui/cterm/term) so I don't think it is necessary that we set all of them, instead just get the current mode. To my knowledge this mode won't change in the middle of running neovim.
This requires neovim 0.7 so it should be done along with https://github.com/hrsh7th/nvim-cmp/pull/844
=> Move highlights to nvim_set_hl lua API

lua/cmp/utils/keymap.lua
Fix https://github.com/neovim/neovim/issues/18303
This can be slower, I don't know how frequently this function is called as I don't use this plugin.
=> fix: use scratch buffer and lhs for keymap.normalize()

lua/cmp/utils/keymap.lua
`keymap.normalize` is called many times when creating a buffer, so I think it makes sense to reuse the scratch buffer for it.
=> Reuse scratch buffer for keymap normalization

lua/cmp/init.lua
I ran into some issues with indenting/unindenting code via `<C-d>/<C-t>` when the completion menu was open but no docs window visible.
I was also a bit surprised to see that when indenting/unindenting code it also opens the completion menu, which feels like a potential separate issue?
=> fix: only scroll docs if docs view is visible

doc/cmp.txt, lua/cmp/core.lua, lua/cmp/view.lua
Add more events.
This allows the following behaviour (notice the up/down arrow pointing to the direction of the menu (top_down or bottom_up):
Here is the code needed to implement it, assuming you are using the `custom` view, and setting `selection_order` to `near_cursor`:
```lua
local ns_id = vim.api.nvim_create_namespace('arrows')
local function remove_marks()
local all = vim.api.nvim_buf_get_extmarks(0, ns_id, 0, -1, {})
for _, mark in ipairs(all) do
vim.api.nvim_buf_del_extmark(0, ns_id, mark[1])
end
end
cmp.event:on('view_closed',
function()
remove_marks()
end
)
cmp.event:on('view_opened',
function(evt)
if vim.api.nvim_get_mode().mode:sub(1, 1) == 'c' then
return
end
local character
local cursor = vim.api.nvim_win_get_cursor(0)
local row = cursor[1] - 1
local col = cursor[2] …
```
=> add events: view_opened and view_closed

lua/cmp/entry.lua, lua/cmp/types/lsp.lua
Fixes #985 among others
This PR allows sources to return custom completion item kinds by returning a string instead of a int in the kind field. Currently, if you have a source which does not fit into the categories of a normal snippet or lsp kind there is no way to add an additional field. This fixes that. Here is an example in my copilot plugin:
```
source.format_completions = function(_, params, completions)
return {
label = label,
kind = "Copilot",
...
}
end
```
The benefits to this implementation (besides being 2 lines of code) are that highlight groups will be automatically added, for instance:
`vim.api.nvim_set_hl(0, CmpItemKindCopilot, '#A5BA93')`
Since cmp doesn't read config for formatting until immediately after determining type, this is by far the easiest way of making …
=> feat: Custom item kinds

lua/cmp/types/cmp.lua
Side note, where is this documented? I see sumneko warning me about not providing an argument to cmp.mapping.complete(), but I don't know what the options object even does.
=> Fix type comment for cmp.ContextReason

lua/cmp/entry.lua
Fixes #1030 
After looking at the input ```matcher.match``` got from the reproduction steps in the bug report, it looks like the signature of a function call was forgotten to be updated in c073501
=> fix: matched highlighting dissapearing

lua/cmp/view/native_entries_view.lua
The dictionary returned by `pum_getpos()` uses `scrollbar` not
`scrollable` to indicate whether the scrollbar is visible or not.
In addition, the padding on the left side of the popup menu isn't
included in the output of `pum_getpos()`, meaning that both `col` and
`width` (as understood by nvim-cmp) are off by one when the cursor isn't
at column `0`.
These two issues were causing the documentation window and popup menu to
overlap.
=> Fix native_entries_view.info width and col calculations

utils/vimrc.vim
=> Use `cmp.config.sources` in minimum vimrc

lua/cmp/view/docs_view.lua
As you can see, I have added file types for docs-view.
This will be more friendly to some plugins, such as: [nvim-colorizer.lua](https://github.com/norcalli/nvim-colorizer.lua)
When there is no file type, no color is displayed:
With the file type:
=> add docs view filetype

nvim-cmp-scm-1.rockspec
so that other plugins can mark nvim-cmp as a dependency
Some justification there https://teto.github.io/posts/2022-06-22-neovim-plugin-luarocks-2.html
=> feat: add rockspec

lua/cmp/entry.lua
fixes cmp.mapping.confirm when ConfirmBehavior is set to Replace
----
Some servers send a `TextEdit` in the following form
```
{
newText = '"javascript.suggest.names": ${1:true}',
range = {
end = {
character = 0,
line = 2
},
start = {
character = 0,
line = 2
}
}
}
```
Before/after:
https://user-images.githubusercontent.com/109605931/185707880-4819cc3e-1408-4748-940d-845f22a27073.mp4
I've seen this behavior on cssls/html/jsonls/gopls.
See: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit and https://github.com/LunarVim/LunarVim/issues/2876#issuecomment-1204393574.
Repro:
<details>
vimrc.vim
```vimscript
if has('vim_starting')
set encoding=utf-8
endif
scriptencoding utf-8
if &compatible
set nocompatible
endif
let s:plug_dir = …
```
=> fix(entry/get_replace_range): handle TextEdit.range

lua/cmp/utils/misc.lua
When using incsearch with cmp-cmdline, the completion window display may be corrupted.
By default, it uses `<Up><Down>`, but you can re-render it by using `<C-r><Esc>` or `<C-r><BS>`.
However, using `<C-r>` breaks the history going back with `<Up>` and `<Down>`.
Therefore, a configuration item has been added to allow the user to change the key to be sent.
https://user-images.githubusercontent.com/5423775/187353553-2e3ec752-3a52-43fc-9781-2663905a53aa.mp4
=> Add incsearch_redraw_keys settings

lua/cmp/utils/async.lua
When running debug builds of Neovim which defines `EXITFREE`, not closing the timers will cause exit to hang whilst Neovim manually frees them.
=> fix(timer): close timers before Neovim exits

README.md
The use of "setup" in "Setup nvim-cmp" and "Setup lspconfig" is incorrect because "setup" is a noun while "set up" is a verb. "Set up" is correct.
=> Fix grammar mistake: "setup" -> "set up"

doc/cmp.txt, lua/cmp/source.lua, lua/cmp/types/cmp.lua
This allows the user to specify a `filter` function for each source.
Solves:
https://github.com/hrsh7th/nvim-cmp/issues/1036
https://github.com/hrsh7th/nvim-cmp/issues/1041
https://github.com/hrsh7th/nvim-cmp/issues/806
@hrsh7th do you see any problems with this implementation or approach in general?
An example (Updated):
```lua
-- don't show entries with kind "Text" from the "nvim_lsp" source
sources = {
{
name = "nvim_lsp",
entry_filter = function(entry, ctx)
local kind = types.lsp.CompletionItemKind[entry:get_kind()]
if kind == "Text" then return false end
return true
},
}
```
By utilizing the `ctx` parameter, the user can also ignore certain
entries in certain contexts.
Notes:
- <s>The name `filter` might not be entirely clear; what does returning `true` or `false` actually result in? …
=> feat: add `filter` option to sources

README.md
Since we can use both `/` and `?` for searching in Neovim, it makes more sense to use the buffer source in both of them instead of just `/`. Since putting `{ '/', '?' }` instead of `'/'` does not work, I put it in a `for` loop.
=> `README.md`: use buffer source for `/` and `?`

nvim-cmp-scm-1.rockspec
sry I made an error when I first submitted the rockspec. I realized that while trying to use it in nixpkgs. This should fix it. Diff is bigger because I reformatted the file with stylua as well.
=> fixed rockspec copy_directories

README.md, lua/cmp/config.lua
I made the `cmd.setup.cmdline` function support using a string or a table as the first argument. Since it is recommended to have the same configuration for both `/` and `?`, this makes a lot of sense so we do not have to use a `for` loop. I also changed the README since we do not need the `for` loop anymore.
=> `setup.cmdline`: support using a table

lua/cmp/config.lua, lua/cmp/types/cmp.lua
Updated type annotations as `setup.cmdline` now accepts string[] by #1193.
=> Update type annotations for setup.cmdline

lua/cmp/entry.lua
fixes #1156, supersedes #1148 and does not regress #1140
=> fix(get_replace_range): workaround for end char matching cursor position

lua/cmp/config/context.lua
`in_treesitter_capture` used to compare a node:type() with what should be a capture, returning always a falsy value.
The example https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#disabling-completion-in-certain-contexts-such-as-comments did not work as expected, being in_treesitter_capture("comment") always not true.
Now it works as expected.
=> fix(context): `in_treesitter_capture`

lua/cmp/config/context.lua
`get_captures_at_position` has been renamed to `get_captures_at_pos`: neovim/neovim#20331. Fallback to `get_captures_at_position` in case `get_captures_at_pos` is `nil`.
_See comment by @smjonas in https://github.com/hrsh7th/nvim-cmp/issues/1211#issuecomment-1273592539_
=> fix(context): compatibility with nvim<0.8

doc/cmp.txt
Ran into a bug in the help file showing an example source. There was a stray `source.new()` call that threw errors. This PR might save somebody in the future a bit of head-scratching.
=> Fix undefined new() error in example source

doc/cmp.txt, utils/vimrc.vim
Commit 0b6654d3de257669b9b3b2a5cb557d5d813f2229 changed the `README.md` to use `default_capabilities()` instead of `update_capabilities()`. This commit replicates that change to `doc/cmp.txt` and `utils/vimrc.vim` for consistency.
=> Use `default_capabilities()` in doc and util

doc/cmp.txt
nvim-treesitter supports language injection in help docs.
see:
https://github.com/nvim-treesitter/nvim-treesitter/pull/3846
=> Docs: Use tree-sitter language injection

lua/cmp/entry.lua
The issue is that when the `start` and `end` of the range are the same. `convert_position_encoding` will return the same exact table back for each because the first call will be cached and then returned on the second. `cmp.confirm` modifies the `start` and `end` of the converted range in different ways but because they refer to the same table, modifying `start` modifies `end` and vice versa. The solution is to convert the whole range instead of the `start` and `end` parts separately.
This fixes #1344.
=> fix(entry): convert encoding of whole range instead of start / end separately

lua/cmp/utils/window.lua
Ever since neovim introduced the nvim_ui_pum_set_bounds() call, GUI clients have gained the ability to inform neovim of the current bounds of an external popup menu provided by ext_popupmenu.
Since external popup menus are allowed to be any size in pixels which may or may not line up cleanly on the grid, nvim allows for fractional coordinates to be reported. This also will mean that in the event of this, we'll end up with a cmp.WindowStyle with a float value for width/height - which is incompatible with vim.api.nvim_open_win() and will cause us to hit errors with GUI clients using this API call. An example:
```
Error executing vim.schedule lua callback: /home/lyudess/.vim/bundle/nvim-cmp/lua/cmp/utils/window.lua:115: 'width' key must be a positive Integer
stack traceback:
[C]: in function …
```
=> Round up width/height for windows

lua/cmp/utils/window.lua
This PR solves #1413
I found a better way then using the `:noautocmd` ex-command. Temporarily setting `eventignore` solves the issue
=> Setting local window options does not trigger the "OptionSet" event

lua/cmp/utils/options.lua, lua/cmp/utils/window.lua
Sorry for the git crazyness, im still learning and not very comfortable with rebasing etc.
Anyway: I reverted the last commit because I missed some nvim_{win,buf}_set_option commands. Since there are many of them, I created a wrapper function to avoid duplicate code. As of now, the OptionSet event is never triggered.
Closes https://github.com/hrsh7th/nvim-cmp/issues/1413
=> Improved: ALL option settings do not fire the `OptionSet` event

lua/cmp/config/mapping.lua
Hi! dear maintainers - this small contribution is to add the missing mappings to fully mimic Neovim's native completion behavior.
Signed-off-by: Wuelner Martínez <wuelner.martinez@outlook.com>
=> feat(mapping): add all native mappings

lua/cmp/entry.lua
When the common overlap between the candidate we're trying to complete and the characters after the cursor is less than 2, nvim-cmp will fail to de-duplicate that redundant character. For example, trying to complete `foobar` in `foob|r` will get you `foobarr`.
This fix ensures that last character of the candidate also gets checked.
Ref: https://github.com/hrsh7th/nvim-cmp/issues/1463
=> fix: de-duplicate completion correctly

lua/cmp/config/mapping.lua
Annotates the complete option as optional. The current suggest default complete mapping without parameters `cmp.mapping.complete()` throws a `missing-parameter` warning if having added the cmp dir to runtime for type assistance.
=> fix: annotate complete option as optional

nvim-cmp-scm-1.rockspec
Fixes the missing documentation was missing when installing through luarocks.
=> fix(rockspec): add doc folder

doc/cmp.txt
The way nvim-cmp inserts text can be controlled via the `behavior` option (part of `ConfirmOption`). There are many tutorials mentioning those, and they are well received.
Yet, the documentation does not mention them.
This PR adds a bit of documentation what options are available, and how they differ.
=> Document cmd.ConfirmBehavior options

lua/cmp/config/compare.lua
fix: https://github.com/neovim/neovim/pull/22761
=> fix: Use vim.treesitter.get_node_text() to avoid deprecation warning

lua/cmp/entry.lua, lua/cmp/entry_spec.lua
1. With `string.byte(self.context.cursor_line, idx) == nil` it was evaluating to true which doesn't seem correct. But usually it happen for trailing byte, so idx returned was actually equals to `offset`.
```lua
char.is_white(string.byte(self.context.cursor_line, idx))
```
2. When all the chars are whitespaces, the actual offset returns and number of spaces, but the first element index should be +1.
=> fix: #1533

lua/cmp/view/ghost_text_view.lua
Fix #1565. 
Somehow, commit [5a80cd4](https://github.com/hrsh7th/nvim-cmp/commit/5a80cd4eca61cd4f5e10165bbb5dc5411d6a5a76) introduce a regression where `experimental.ghost_text` cannot be enabled with a boolean anymore.
This fix check first the type of the ghost_text config before applying the highlight.
=> fix(ghost_text): safely apply virtual_text highlight

doc/cmp.txt
The documentation that explained ConfirmBehavior had typos and lacked a configuration example. This commit fixes the typos and provides an example configuration.
=> docs: fix typos, add confirm.behavior example cfg

README.md
This seems to fix #1584. (See the rich diff; the video actually shows up and can be played).
=> Fix demo video in README.md

lua/cmp/entry.lua
fix entry highlight after #1583
=> fix entry highlight in complete-menu

lua/cmp/core.lua
This fixes #1119 (basically using the solution prescribed there, except `misc.safe` is no longer a function). I'm not super familiar with LSP, but I use neovim and godot frequently and would like to see this working. Let me know how I can improve this. In my testing this fixed the issue and didn't cause any noticeable side-effects.
=> fix: handle godot LSP better

lua/cmp/entry.lua, lua/cmp/utils/async.lua
=> fix(async): properly trigger callbacks when canceling and fix delays in `throttle.sync`

lua/cmp/core.lua
Solve the performance issue of #1433.
I wrote a function with the same semantics as the regular expression to replace it. The function searches for a non-empty character suffix starting from the end of the line.
Since the string is huge, it still appears slow, but it can avoid freezing.
=> fix: huge single line performance (#1433)

lua/cmp/types/cmp.lua
Fix type of ghost_text to not create a warning when set to true
The existing type appears to be forcing the user to supply a table containing a hl_group for ghost text by specifying a value of false otherwise,
and yet the ghost text implementation clearly allows a value of ghost_text other than a table with hl_group by defaulting to 'Comment'
=> fix: allow ghost_text type to accept values of true

lua/cmp/types/cmp.lua
I have fixed it to match the following as described in the help
> completion.autocomplete
>   `cmp.TriggerEvent[] | false`
=> fix type of the config.autocomplete to accept false

plugin/cmp.lua
Previously `vim.api.nvim_replace_termcodes('<C-c>', true, true, true)` was called every time the `CursorMoved` autocommand event fired. Even though afaik there is no reason to do so as the termcode stays the same. I discovered this by profiling with [profile.nvim](https://github.com/stevearc/profile.nvim) while trying to fix another issue (unrelated to cmp).
Feel free to change the variable name.
=> perf: fix `nvim_replace_termcodes` being called on every `CursorMoved`

.gitignore, doc/cmp.txt, lua/cmp/config/default.lua, lua/cmp/config/mapping.lua, lua/cmp/init.lua, lua/cmp/types/cmp.lua, lua/cmp/view.lua
Refer to #1646 
I'm very sorry for the trouble, for some reason GitHub stopped showing all my commits (??).
=> feat: add toggle_doc functionality

lua/cmp/core.lua
Call `string.match()` once instead of calling `string.sub()` and `string.find()` multiple times in a loop.
=> perf(core): simplify and improve `find_line_suffix()`

lua/cmp/view/ghost_text_view.lua
I'm on neovim nightly and inline `ghost_text` was not working for me. TL;DR: `ephemeral` option seems to somehow cause the check for inline virt-text support to fail, while it's actually supported.
I noticed you check for inline virt-text support here:
https://github.com/hrsh7th/nvim-cmp/blob/2743dd989e9b932e1b4813a4927d7b84272a14e2/lua/cmp/view/ghost_text_view.lua#L12-L22
So, I ran it to see whether it reports if I have inline support or not and I got an error back:
```lua
local ns = vim.api.nvim_create_namespace('thing')
local id = vim.api.nvim_buf_set_extmark(0, ns, 0, 0,{
virt_text = { { ' ', 'Comment' } },
virt_text_pos = 'inline',
hl_mode = 'combine',
ephemeral = true
})
vim.api.nvim_buf_del_extmark(0, ns, id)
```
```
E5108: Error executing lua [string ":lua"]:1: not yet implemented …
```
=> fix(ghost_text): `ephemeral` causes inline virt-text support check to fail

lua/cmp/config/compare.lua, lua/cmp/types/cmp.lua
Also added type annotation `cmp.Comparator` for sorting.comparators
=> docs: Add comments and type annotations for sorting comparators

lua/cmp/core_spec.lua, lua/cmp/utils/feedkeys_spec.lua
The `backspace` setting only accepts strings.
Here, I assume that 0 was intended to set
backspace to a nil value, which can be done with
the empty string.
=> ci: fix broken tests

lua/cmp/entry.lua, lua/cmp/utils/str.lua, lua/cmp/view/ghost_text_view.lua
This function is [now deprecated](https://github.com/neovim/neovim/pull/25733).
=> fix: remove usages from vim.lsp.util.parse_snippet

lua/cmp/view/ghost_text_view.lua
This is a workaround to get inline ghost-text to work as expected without using ephemeral extmarks. See refs for context.
Refs:
- https://github.com/hrsh7th/nvim-cmp/pull/1645
- https://github.com/neovim/neovim/issues/24797
=> fix(ghost_text): ephemeral-like inline ghost-text workaround

lua/cmp/types/cmp.lua
I have been getting "Missing required fields" messages from lua-language-server (`> 3.6.23`) for table values handed to `require('cmp').setup()`.
This is a naive attempt to fix those missing required fields messages. I'm still fairly new to Lua, but happy to learn! 
Please let me know if I've missed any others that are optional so I can get those marked too.
Once applying this patch to a local checkout of `nvim-cmp`, I don't get missing field diagnostic messages anymore.
Thanks for considering my patch!
=> Mark non-required setup fields as optional

doc/cmp.txt
Typos fixed in doc/cmt.txt file:
ammount -> amount
ommited -> omitted
additionaly -> additionally
=> Fixed typos in cmp.txt file

lua/cmp/config/window.lua
This commit differentiates the border color from the inner content color of the nvim-cmp float. The `FloatBorder` group links to `VertSplit` by default and is usually set by the colorscheme, so this commit makes nvim-cmp match with other float window colors. 
Say this is our usual LSP float window:
Previously our cmp window looks like this:
Now it will match the LSP window (and other floating windows):
This was discussed in #748 but was closed without any change.
NOTE: This commit changes the default for `config.window.bordered`, but the borderless default remains the same since there is no border there anyway. If one was added the border would look as it does in the old way but at that point the user would probably be configuring everything manually anyway.
=> feat: match default border color to standard neovim float border hl

lua/cmp/view/custom_entries_view.lua
When I try to open a file with `-M` option. 
**command:** `nvim -M <filename>`.
The completion of commandline will be break.
I found that `nvim_buf_set_lines` cannot work when the buffer is `unmodifiable`.
Add judgement before 'nvim_buf_set_lines': if the buffer is `unmodifiable`, make it `modifiable` temporarily.
I think #1113 is relative to this problem.
=> Fix: Buffer is not 'modifiable'

lua/cmp/source.lua, lua/cmp/view.lua
Hi,
When using the prop `max_item_count`, there is a known catch (sorting issue) from the doc:
```
sources[n].max_item_count~
`number`
The source-specific maximum item count option
Note: This is applied before sorting, so items that aren't well-matched may be selected.
```
This PR makes it so the source entries are sorted before being sliced and fed to the full list of entries and then sorted again.
If the performance hit is too big, we could maybe add an optional boolean option such as `sort_before = true` along with `max_item_count`, to make sure the user still wants this sorting to happen even if it is slower.
EDIT:
Just had another thought... We could maybe avoid all this sorting X times per source + 1 time per group index, while still keeping the results accuracy, but it would bring …
=> feat: sort source entries before slicing when using max_item_count

.github/workflows/release.yaml
Hey!
Since the Luarocks releases CI was outdated, I have made some changes to update and improve it.
---
Ps: it would be nice if you made a new tag after this one is merge so that `nvim-cmp` is available in luarocks (the last tag was in 2022 so the CI hasn't really been used yet 😞)
=> feat(ci): update luarocks-tag-release to latest version

lua/cmp/view.lua
I found `nvim-cmp` always displays one more item than the `source[n].max_item_count`.
I checked the implementation, which seems to be working like if `max_item_count` is greater **or equal to** zero, append one item and reduce the `max_item_count` by one :)
=> fix: one more item than max_item_count is displayed

README.md, doc/cmp.txt, lua/cmp/config/default.lua, lua/cmp/entry.lua, lua/cmp/matcher.lua, lua/cmp/matcher_spec.lua, lua/cmp/types/cmp.lua
The no_symbol_match makes command line completion a lot less useful. It disables any matches for file names with symbols in them. This prevents completing things like ":b foo/bar" to ":b foo/bar.txt" or ":b foo_" to ":b baz/foo_bar.txt". Add an option `disallow_symbol_nonprefix_matching` that prevents a match if it contains a symbol and isn't a prefix match. Make that option the default. Add the option to documentation and tests. Add to the examples for command line setup disabling the option.
=> Add option for symbol matching logic.

lua/cmp/utils/window.lua, lua/cmp/view/custom_entries_view.lua
Fixes #827 and #1759
The `entries_win:open` function will fail when either the width or the height of the window is less than 1, which will result in the `nvim_win_set_cursor` being passed a `nil` value for `self.entries_win.win` instead of a number, which causes an error to constantly appear when the window is small. Hence, a guard clause to check for whether `self.entries_win.win` is `nil` is added to stop the error from occurring.
Also fixed the rarer 'height' must be a positive Integer error caused by the `window.update` function, within the clause to draw the scrollbar background. This error happens on small windows when pressing and holding down the backspace key to delete a lot of characters at once. The `nvim_open_win` function call to create the scrollbar background throws the …
=> fix: small windows no longer constantly throw errors

README.md, doc/cmp.txt, lua/cmp/config/default.lua
Neovim v0.10 is introducing a native snippet engine. It seems like a good default to configure that for snippet expansion if it is available. Let me know what you think and if I should include any more details in the documentation!
=> feat: default to `vim.snippet` for snippet expansion if available

lua/cmp/types/cmp.lua, lua/cmp/view/custom_entries_view.lua
Problem: `cmp.WindowConfig` was defined twice, and not consistent with docs |cmp.txt|.
Solution: Introduce `cmp.CompletionWindowOptions` and `cmp.DocumentationWindowOptions`.
Make fields of these two class consistent with |cmp-config.window.*|
=> docs: fix invalid WindowConfig schema, should match to the docs

lua/cmp/entry.lua
Fix/workaround for #1705
"Workaround" because I think ultimately the issue is in the Astro language server or an upstream language server returning wrong ranges for `completionItem/resolve` requests.
Excuse me if there is a reason this behaviour is undesirable. Since the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) says that properties provided in `textDocument/completion` "must not be changed during resolve" and VS Code presumably (I don't know where its code for handling completions is) behaves like this, as it's not affected by the above issue, I kind of assume this would be fine.
Also, just out of curiosity, is there a reason this doesn't use `vim.tbl_extend()`?
=> Favor existing values in completion_item over resovled_completion_item

doc/cmp.txt, lua/cmp/view/docs_view.lua
To allow for using all available screen space, as we can omit a max_height/max_width when creating a documentation popup). I've found this to be useful with neovim-gtk's native GUI completion menus.
=> Allow window.documentation.max_{width, height} to be set to 0

doc/cmp.txt, lua/cmp/config/default.lua, lua/cmp/types/cmp.lua, lua/cmp/view/custom_entries_view.lua, lua/cmp/view/docs_view.lua
Set cmp window's `winblend` to `pumblend` makes it consistent with neovim itself, but there is a case:
As you can see above, some of the nerd icons on the left side of the window are small, that's because terminals render nerd icons as two characters wide if there is a space on their right. If `pumblend` is set, the right of the nerd icon will be a character under the window instead of a space. So I think a positive value of `winblend` is not suit for cmp in some case.
In current implementation, there's no way to make cmp's winblend different from other popup windows, if I want to change cmp, I must change them all. So I recommend making this option configurable.
=> feat: make winblend configurable

doc/cmp.txt, lua/cmp/config/default.lua, lua/cmp/types/cmp.lua, lua/cmp/view/custom_entries_view.lua
~~Creates an option to allow the custom entries
view to follow the user's cursor as they type.~~
This PR adds an option to allow the view, both custom and native, to follow the user's cursor as they type.
To enable, set
```lua
require("cmp").setup({
view = {
entries = {
follow_cursor = true
}
}
})
```
Original custom view source at https://github.com/lvimuser/nvim-cmp/commit/7569056388417d887baf2e959e18a767bcfe84f1
Closes #1660
=> feat: add option for view to follow cursor

doc/cmp.txt
- correct view.follow_cursor to view.entries.follow_cursor
- mention that view.entries.follow_cursor is custom view only
- add missing view.entries.selection_order option
- mention the docs class in list of classes nested under view class
- trim errant whitespace
=> docs: update and fix `view` documentation

lua/cmp/config/default.lua
Evaluating `vim.snippet` loads many modules, which takes about 1ms.
=> perf: don't eagerly load vim.snippet

lua/cmp/init.lua
Fix #1251 and #1919. This comment was very helpful for me. (https://github.com/hrsh7th/nvim-cmp/issues/1251#issuecomment-1365229958)
=> fix: unexpectedly re-open a completion window when setting `autocomplete = false`

lua/cmp/init.lua
Fix https://github.com/hrsh7th/nvim-cmp/issues/1919.
cf. https://github.com/hrsh7th/nvim-cmp/pull/1920
Now, `autocomplete = false` got more cozy!
=> fix: `cmp.close()` when `autocompletion = false`

lua/cmp/utils/misc.lua
`vim.tbl_islist` will be deprecated on 0.12. This make use of their replacement. I'm not sure what's the minimum version this function is available though...
=> Move to non deprecated function calls

lua/cmp/view/ghost_text_view.lua
This is a simple PR that enables ghost text when the completion candidate has multiple lines. For example, suggestions from Copilot, or multi-line completions provided by a language server:
This also partially addresses #1862: if the completion candidate contains multiple lines, then this PR will allow them to be displayed. But to keep the scope small, this PR does not handle expanding snippets. That will need to be solved in another PR to resolve #1862
I know this is unsolicited, so no pressure to merge. But it's a feature I want, and it seemed easy enough to implement so I thought I would offer.
Please let me know if you have any questions, or if there's anything you would like me to change.
Thank you!
=> enable ghost_text for multi-line completions

lua/cmp/utils/feedkeys.lua, lua/cmp/view/ghost_text_view.lua
This seems to fix #1560 in my limited testing. It would be great if anyone else can test it and see if any other issues arise.
and https://github.com/zbirenbaum/copilot-cmp/issues/79
At the very least, we should include the pcall to stop it from crashing cmp entirely in the event of a bad completion,
This is required after neovim deprecations here:
https://github.com/neovim/neovim/pull/24350
=> fix(feedkeys): resolve issue with some copilot completions

lua/cmp/init.lua, lua/cmp/view.lua, lua/cmp/view/custom_entries_view.lua, lua/cmp/view/native_entries_view.lua, lua/cmp/view/wildmenu_entries_view.lua
API to get the number of the currently selected candidate, which can be combined with get_entries to find out "what are the entries above and below".
=> feat(view): add api get_selected_index

lua/cmp/config/compare.lua
A few hours ago, the [nvim-treesitter main branch removed `locals.get_scopes` for the newer `locals.get`](https://github.com/nvim-treesitter/nvim-treesitter/commit/0297cc6182fa7bf9608777c180172c35553d6a26#diff-eed1b34be50be29ccfe659070eb48f6ed610abaa7d984e3c5b8ac112cb1cfa38) so this PR adds a fallback to the newer method to help those trying out that branch.
=> fix: Add newer fallback method for tree-sitter scopes

.github/workflows/integration.yaml, lua/cmp/config/compare.lua, lua/cmp/core.lua, lua/cmp/entry.lua, lua/cmp/entry_spec.lua, lua/cmp/source.lua, lua/cmp/types/lsp.lua, lua/cmp/utils/cache.lua, lua/cmp/view.lua, lua/cmp/view/custom_entries_view.lua, lua/cmp/view/ghost_text_view.lua, lua/cmp/view/wildmenu_entries_view.lua
nvim-cmp is still not ideally responsive when dealing with huge list of completion items, especially with tailwindcss which sends thousands of candidates on each completion response: #1009 #1828 #1949. Though some improvements have been done before but cmp is still apparently slower than other completion engine like vscode and coc.nvim in extreme cases.
This PR extracts two commits from [my experimental perf branch fork](https://github.com/yioneko/nvim-cmp/tree/perf) which I think could be better upstreamed. The details and rationales are explained in commit descriptions.
The commits introduce massive changes to the codebase, and I'm not sure if you'd like to accept them. Since the changes are made just for improving performance in extreme cases, it's totally fine for me if you consider …
=> perf: improve for source providing huge list of items

lua/cmp/view/ghost_text_view.lua
This fixes a problem with Neogit is discussed here:
https://github.com/NeogitOrg/neogit/discussions/1492
=> Avoid calling del_extmark on non existing buffer

lua/cmp/utils/keymap.lua
After https://github.com/hrsh7th/nvim-cmp/pull/986, @zeertzjq added the `keytrans()` function for translating byte rep of keys to key notation form in https://github.com/neovim/neovim/commit/907fc8ac373226556b84c2fdc4fe26525bbdb2c4. This can be used for normalization. 
This reduces running time of `prepare()` from about 16ms to 6ms on my setup. 
btw I' curious about why `keymap.t` manually replaces `<` instead of using `nvim_replace_termcodes` (https://github.com/hrsh7th/nvim-cmp/pull/720/commits/f2f6dce0cc708ebea904ed471849e1d62a19cf96). `nvim_replace_termcodes` is slightly faster.
=> perf: use builtin for key normalization

lua/cmp/utils/keymap.lua
Fix https://github.com/hrsh7th/nvim-cmp/pull/1935#issuecomment-2426250159
=> fix: use unsimplified key for keymap.normalize

lua/cmp/entry.lua, lua/cmp/types/vim.lua, lua/cmp/view/custom_entries_view.lua
Related: #1887
This PR allows more highlight control by allowing `vim.CompletedItem.{field}_hl_group` values to be of type `table` with the following structure:
```lua
-- inside the cmp.FormattingConfig.format method
vim_item.abbr_hl_group = {
{ '@function', range = { 0, 5 } },
{ 'Comment', range = { 5, 10 } },
}
```
A simple use case of this is having different highlights for function parameters:
<details>
<summary>Code</summary>
```lua
local format = function(entry, vim_item)
local kind = entry:get_kind()
if vim.tbl_contains({ 2, 3 }, kind) then -- if kind is a Function (2) or Method (3)
local start_index, end_index = vim_item.abbr:find('%(.*')
if start_index then
vim_item.abbr_hl_group = {
{ '@function', range = { 0, start_index - 1 } },
{ 'Comment', range = { start_index - 1, …
```
=> feat: allow more completion highlight control

lua/cmp/utils/misc.lua, lua/cmp/utils/misc_spec.lua
I don't reprecate the issue but this pr potential fix for https://github.com/R-nvim/cmp-r/issues/12
=> support cpying self-referenced table

lua/cmp/utils/keymap.lua, lua/cmp/utils/keymap_spec.lua
Fixes <c-,> and \<c-:\> in the same way <c-;> was fixed
=> fix: make <c-,> and <c-:> work again

lua/cmp/utils/window.lua
=> fix: scrollbar thumb ui issue

lua/cmp/utils/keymap.lua, lua/cmp/utils/keymap_spec.lua
#1935 will cause some symbols to not be mapped correctly. I have added the symbols that I need to map. I'm not very familiar with others' habits, but I believe there should be some other symbols that need to be added to this patter.
Fix #2080.
=> fix: some symbols can't be mapped correctly

lua/cmp/utils/keymap.lua, lua/cmp/utils/keymap_spec.lua
Identical fix to https://github.com/hrsh7th/nvim-cmp/pull/2073
=> fix: make <M-`> work again

README.md
The example configuration is Vimscript, with a heredoc containing some Lua code. Using "lua" as a language identifier results neither the Vimscript portion nor the Lua portion being highlighted propertly.
Mark the code block as "vim".  Neovim (with treesitter) properly highlights the outer block as Vimscript, and the Lua heredoc as Lua code.
=> Mark vimscript block as "vim"

lua/cmp/init.lua
The `CmdwinEnter` handler was changed in 5054c1449079e - this reintroduces it to fix #603
=> Fix completion menu showing over the cmd win

lua/cmp/types/lsp.lua
Fixup for #1931 to use `vim.tbl_keys`, to avoid iterating while adding keys.
Fixes https://github.com/hrsh7th/nvim-cmp/pull/1931#issuecomment-2213094466
Fixes #1939
=> fixup! fix: remove deprecated use of vim.tbl_add_reverse_lookup (#1931)

README.md, doc/cmp.txt, lua/cmp/core.lua, lua/cmp/init.lua, lua/cmp/utils/autocmd.lua
Fixes #2119 
The issue as described by @xzbdmw has been debated in several other places:
[.. triggers completion when it should not ..](https://github.com/abeldekat/cmp-mini-snippets/issues/6)
[beta testing mini.snippets: expanding snippets from lsp](https://github.com/abeldekat/cmp-mini-snippets/issues/9)
@xzbdmw provided a clear explanation:
>>I'll try to explain more detail:
mini.snippets: insert mode -> type 'f' -> both mini.snippets and cmp detects TextChangedI -> cmp-nvim-lsp sends request -> lua_ls receives the buffer content, which is vim.schedule(ffn) -> mini.snippets clears the placeholder fn, it becomes vim.schedule(f) -> "fun" completion_item contains TextEdits that want to clear the fn , now what in fn's original place is now the right pair -> right pair gone, before snippets …
=> fix: Outdated completion item with mini.snippets

lua/cmp/utils/event.lua
Sometimes the cursor freezes for a second and i get a error popup: 
```
Error executing lua callback: ....../event.lua:47: attempt to call local 'callback' ( a table value ) 
Stack traceback:
....
```
so i fixed this, it's only a 3 line change
=> fix(utils): Only call callback if type(callback) == "function"

lua/cmp/core.lua, lua/cmp/utils/api.lua
fixes https://github.com/olimorris/codecompanion.nvim/issues/1060
This change preserves the original `buflisted` state of the current buffer when applying LSP text edits. The function `vim.lsp.util.apply_text_edits` forces `buflisted` to true (see https://github.com/neovim/neovim/issues/12488 and https://github.com/neovim/neovim/pull/12489), which is useful for non-current buffers but not desired for the current one. This fix saves the state before applying edits and restores it afterward.
Same as https://github.com/Saghen/blink.cmp/pull/1432
`make test` and `make lint` passed locally.
=> Preserve 'buflisted' state when applying LSP text edits

lua/cmp/utils/window.lua
neovim 0.11 introduced winborder: https://github.com/neovim/neovim/pull/31074 This means that the user may override the global window border for all windows for which the border wasn't explicitly set. For the scrollbar and the scrollbar thumb, we don't want any border.
In the past we achieved that by not specifying any border, but with winborder, the user may set the border and then the scrollbar looks broken. So now we explicitly say that we want no border on these two windows, fixing the issue.
I tested this commit on neovim 0.10.2 as well, without issues.
To reproduce the issue on neovim 0.11, run:
```
:lua vim.o.winborder = "rounded"
```
and then invoke nvim-cmp on a completion where the scrollbar will be displayed.
=> fix: handle winborder in neovim-0.11

lua/cmp/types/cmp.lua
Similar to https://github.com/hrsh7th/nvim-cmp/pull/1723
Default values are set in https://github.com/hrsh7th/nvim-cmp/blob/ae644feb7b67bf1ce4260c231d1d4300b19c6f30/lua/cmp/config/default.lua#L48 so afaik no need to explicitly require them.
=> fix missing required fields in formatting config
